name: Docker Image CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    env:
      IMAGE_TAG: ${{ github.run_number }}  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pinkysingh/app-repo/react-weatherapp
    - name: List Docker Images
      run: docker images
    - name: Docker Push
      run: docker push pinkysingh/app-repo/react-weatherapp:$IMAGE_TAG
